### ISSUE TITLE
Doesn't check reddit for comments in the comment thread

### ISSUE THREAD

**Issue by willlma** [sajirdalas/alienPlanet#1]
If a link has been posted to reddit, but there are no comments, it still shows up in the _check on reddit_ panel.

**Comment by sajirdalas** [comment]
Good point. This should be easy to fix. Thanks

**Comment by 53245342099** [comment]
I like that it shows up there.  A simple number within parentheses indicating how many comments are on each entry would be nice to see.

**Comment by sajirdalas** [comment]
Yeah, I realized that just now. I will be sure to add that very soon, should not be very hard

**Comment by sajirdalas** [comment]
I have added a comment counter on list mode
